#---------------------------------#
#       build configuration       #
#---------------------------------#

os: Visual Studio 2015
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
platform: Any CPU
configuration: Release

before_build:
  - nuget restore
